### PR TITLE
Export private fields in SimpleElement, CompoundElement and SharedElement

### PR DESCRIPTION
**Pull request by jonamat**
Export private fields to create custom elements 

```go
customElement := &kml.CompoundElement{
    StartElement: xml.StartElement{Name: xml.Name{Local: "Folder"}, Attr: []xml.Attr{{Name: xml.Name{Local: "id"}, Value: "myCustomID"}}},
    Children: []kml.Element{
        kml.Name("My custom folder name"),
    },
}

k := kml.KML(
    customElement,
)

if err := k.WriteIndent(os.Stdout, "", "  "); err != nil {
    log.Fatal(err)
}
```

Output
```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Folder id="myCustomID">
    <name>My custom folder name</name>
  </Folder>
</kml>
```

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks for this :) The Go conventions are that id fields should be named `ID`. Would you mind updating the PR?

**Comment by jonamat** [comment]
No problem! But `ID` field conflicts with this method  `func (se *SharedElement) ID()`
Could I change the name of the method to `func (se *SharedElement) GetID()` but it's a breaking change

**Comment by twpayne** [comment]
Let's remove `SharedElement.ID()` and `SharedElement.SetID()` (both functions) as users can access the `ID` field directly. Once the PR is merged I'll bump the major version of the library to `v2` to reflect the non-backwards-compatible API change.

**Comment by jonamat** [comment]
OK, done and (manually) tested. Previous tests passed successfully

**Comment by twpayne** [comment]
Awesome, thank you!

**Comment by twpayne** [comment]
OK, v2 is now tagged with your changes, so you should now be able to import `github.com/twpayne/go-kml/v2` with the newly-public fields.

**Comment by jonamat** [comment]
I'll do, thank you!

**Pull request merged**
